services:
  handbrake-server:
    image: localhost:5000/handbrake-web-server:0.8.2
    container_name: handbrake-web-server
    user: 1000:1000 # edit to run as user (uuid:guid) with permissions to access your media. 0:0 to run as root (not recommended).
    ports:
      - 9999:9999
    volumes:
      - data:/data
      - media:/video # ensure this path is the same across all containers

volumes:
  data:
  media:
